apiVersion: v1
kind: Service

spec:
        selector:
                app: run-python
                tier: web
        ports:
        - port: 8080
          targetPort: 8080
        type: LoadBalancer

metadata:
        name: run-python-web
        labels:
                app: run-python
